### ISSUE TITLE
start

### ISSUE THREAD

**Issue by ysakovs** [cypherbits/omeglit#1]
hmm.. how to start this app?

**Comment by ysakovs** [comment]
There just no options to run this script. :( in package in not script start

**Comment by cypherbits** [comment]
Hi, I will try to document it later.

**Comment by cypherbits** [comment]
Hello, I just updated some things. 
You can run it on localhost by running `node main.js --localhost`.

**Comment by ysakovs** [comment]
Thank you for your answer!
But cant run on localhost. it ask for certificate keys...

**Comment by cypherbits** [comment]
Did you update git? ...

**Comment by ysakovs** [comment]
Yes, sure!

**Comment by ysakovs** [comment]
Hi! So you check the script?

**Comment by cypherbits** [comment]
I did update the peoject... Did you update your repo and followed the new instructions on readme? Just need to run node main.js --localhost

**Comment by ysakovs** [comment]
> I did update the peoject... Did you update your repo and followed the new instructions on readme? Just need to run node main.js --localhost

Yes! I download updated! And run on localhost by the code run node main.js --localhost . But then i get notificstion than sertificste keys not found

**Comment by ysakovs** [comment]
https://i.ibb.co/FYtjJhX/ssss.png

**Comment by cypherbits** [comment]
You don't need the [ and ] ...

**Comment by ysakovs** [comment]
Thank you! But app still not running! I cant press on Text OR Video buttons. And no users online count works..
https://www.screencapture.com/faa3640a-91ec-418c-b79b-48d9080d5244

**Comment by ysakovs** [comment]
You can see this issue on this image!
https://s3.gifyu.com/images/screenrecording.gif

**Comment by cypherbits** [comment]
that is weird since the .js/omeglo.js should have localhost configured: 
```
var URLConnection = "localhost:8080";
var URLProtocol = "http://";
```
Do you have this in that file?
Can I see the Chrome console output to see what is failing?

**Comment by ysakovs** [comment]
Yes i have that lines on omeglo.js file...

https://i.ibb.co/tDf2WYM/wwwww.png

**Comment by cypherbits** [comment]
Hi, I think you updated the socket.io library... it says version 4 when the package of this app says we need 2.3.*

> https://i.ibb.co/FYtjJhX/ssss.png

**Comment by ysakovs** [comment]
Yes! you are right!  Thank you!

**Comment by ysakovs** [comment]
I found one issue! When i disconected from video chat and connecting again , video from stranger not showing...

**Comment by cypherbits** [comment]
Just updated it to 2.4.1 to fix a vulnerability. But it should still work fine.

**Comment by ysakovs** [comment]
Thank you for your reply! But update to 2.4.1 not fix video issue..

**Comment by cypherbits** [comment]
The project needs a major refactor... but I don't have time right now since this was just a test to know WebRTC technology years back. Maybe in the future I refactor it all. I will close this issue now.
